import { NextUIProvider } from "@nextui-org/react";
import { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import ButtonGroup from "@/components/ButtonGroup/ButtonGroup";

const inter = localFont({
  src: "../styles/fonts/Inter,Merriweather,Montserrat/Inter/static/Inter_18pt-Regular.ttf",
  variable: "--font-inter",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <NextUIProvider>
          <ButtonGroup>{children}</ButtonGroup>
        </NextUIProvider>
      </body>
    </html>
  );
}
